name: Pipe Selenium-Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Setup ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          mv chromedriver /usr/local/bin/

      - name: Run tests with Chrome (headless)
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: mvn test -DENV=hmg-actions -DBROWSER=chrome-headless

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
