name: Continuous Integration (CI)

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  
          
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
          maven-version: '3.8.1'

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run Cucumber Tests
        run: mvn test

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-reports.html