name: Pipe Selenium-Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-e2e:
    runs-on: ubuntu-latest  # Ambiente de execução

    steps:
      # 1. Fazer o checkout do código
      - uses: actions/checkout@v3

      # 2. Configurar o JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # 3. Construir o projeto com Maven
      - name: Build Project
        run: mvn clean install -DskipTests

      # 4. Usar uma ação do GitHub para configurar o ChromeDriver
      - name: Set up ChromeDriver
        uses: actions/setup-chrome-driver@v1  # Ação que configura o ChromeDriver

      # 5. Executar os testes com Chrome (headless)
      - name: Run tests with Chrome (headless)
        run: mvn test -DENV=hmg-actions -DBROWSER=chrome-headless

      # 6. Upload do relatório HTML do Cucumber
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
