name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Copy ChromeDriver for Linux
      run: |
        cp drivers/chromedriver_linux64 drivers/chromedriver
        chmod +x drivers/chromedriver  # Garante que o driver tenha permissão de execução

    - name: Set up ChromeDriver path for testing
      run: |
        echo "CHROMEDRIVER_PATH=drivers/chromedriver" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
